apiVersion: integer.verity.supply/v1alpha1
kind: ImageDefinition
name: etcd
description: "etcd distributed key-value store — Copa can't patch Alpine/scratch-based official image; Wolfi rebuild"
upstream:
  package: etcd
versions:
  - version: "3"
    latest: true
    tags: ["3", "latest"]
    types: [default, fips]
