apiVersion: integer.verity.supply/v1alpha1
kind: ImageDefinition
name: haproxy
description: "HAProxy load balancer — Wolfi rebuild from source with <24hr CVE response"
upstream:
  package: haproxy
versions:
  - version: "3.0"
    eol: "2029-04-01"
    tags: ["3.0"]
    types: [default, fips]
  - version: "3.1"
    eol: "2026-03-01"
    tags: ["3.1"]
    types: [default, fips]
  - version: "3.2"
    eol: "2030-04-01"
    tags: ["3.2"]
    types: [default, fips]
  - version: "3.3"
    eol: "2027-01-01"
    latest: true
    tags: ["3.3", "latest"]
    types: [default, fips]
