apiVersion: integer.verity.supply/v1alpha1
kind: ImageDefinition
name: node-exporter
description: "Prometheus Node Exporter — Copa uses -distroless variant; Wolfi rebuild"
upstream:
  package: prometheus-node-exporter
versions:
  - version: "1"
    latest: true
    tags: ["1", "latest"]
    types: [default]
