apiVersion: integer.verity.supply/v1alpha1
kind: ImageDefinition
name: mariadb
description: "MariaDB database server — Wolfi rebuild eliminates persistent Debian CVEs"
upstream:
  package: mariadb
versions:
  - version: "10.6"
    eol: "2026-07-06"
    tags: ["10.6"]
    types: [default, fips]
  - version: "10.11"
    eol: "2028-02-16"
    tags: ["10.11"]
    types: [default, fips]
  - version: "11.4"
    eol: "2029-05-29"
    tags: ["11.4"]
    types: [default, fips]
  - version: "11.8"
    eol: "2028-06-04"
    latest: true
    tags: ["11.8", "latest"]
    types: [default, fips]
